AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.awslambda.crud::springbootcrud
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  SpringbootcrudFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.awslambda.crud.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .target/springbootcrud-0.0.1-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringbootcrudApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: SpringbootcrudApi
